GRANT SELECT ON {Schema}.UTIL_SYS_ETL_BATCH_STATUS TO {YOUR_USER_ROLE};

GRANT SELECT ON {Schema}.UTIL_SYS_ETL_TASK_QUEUE TO {YOUR_USER_ROLE};

GRANT SELECT ON {Schema}.UTIL_SYS_ETL_BATCH_STATUS_HIST TO {YOUR_USER_ROLE};

GRANT SELECT ON {Schema}.UTIL_SYS_ETL_TASK_QUEUE_HIST TO {YOUR_USER_ROLE};

GRANT SELECT ON {Schema}.VIEW_UTIL_SYS_ETL_TASK_QUEUE TO {YOUR_USER_ROLE};

GRANT SELECT ON {Schema}.VIEW_UTIL_SYS_ETL_TASK_ALL TO {YOUR_USER_ROLE};

GRANT EXECUTE ON {Schema}.UTIL_SYS_ETL TO {YOUR_USER_ROLE};
