CREATE OR REPLACE VIEW {Schema}.VIEW_UTIL_SYS_ETL_TASK_ALL AS
SELECT
    b.BATCH_ID,
    b.BATCH_STATUS,
    b.SCHEDULED_TIME,
    b.BATCH_COMMENT,
    b.ENTRY_TIME        AS BATCH_ENTRY_TIME,
    b.TRIGGERED_TIME,
    NULL                AS BATCH_COMPLETED_TIME,
    t.STEP_PLAN,
    t.TASK_ID,
    t.EXTRACT_TYPE,
    t.EXTRACT_SOURCE,
    t.EXTRACT_COMMAND,
    t.EXTRACT_PARAMS,
    t.EXTRACT_TIMEOUT_SEC,
    t.RESULT_SET,
    t.NAMING_CONVENTION,
    t.LOAD_TYPE,
    t.FIELD_MAPPING,
    t.MERGE_PARAMS,
    t.LOAD_DESTINATION,
    t.LOAD_COMMAND,
    t.LOAD_TIMEOUT_SEC,
    t.TASK_COMMENT,
    t.CLIENT_ACCOUNT,
    t.ENTRY_TIME        AS TASK_ENTRY_TIME,
    NULL                AS TASK_COMPLETED_TIME,
    NULL                AS RUNTIME_ERROR
FROM
    {Schema}.UTIL_SYS_ETL_BATCH_STATUS   b
    JOIN
    {Schema}.UTIL_SYS_ETL_TASK_QUEUE     t
    ON t.BATCH_ID = b.BATCH_ID

UNION ALL

SELECT
    b.BATCH_ID,
    b.BATCH_STATUS,
    b.SCHEDULED_TIME,
    b.BATCH_COMMENT,
    b.ENTRY_TIME        AS BATCH_ENTRY_TIME,
    b.TRIGGERED_TIME,
    b.COMPLETED_TIME    AS BATCH_COMPLETED_TIME,
    t.STEP_PLAN,
    t.TASK_ID,
    t.EXTRACT_TYPE,
    t.EXTRACT_SOURCE,
    t.EXTRACT_COMMAND,
    t.EXTRACT_PARAMS,
    t.EXTRACT_TIMEOUT_SEC,
    t.RESULT_SET,
    t.NAMING_CONVENTION,
    t.LOAD_TYPE,
    t.FIELD_MAPPING,
    t.MERGE_PARAMS,
    t.LOAD_DESTINATION,
    t.LOAD_COMMAND,
    t.LOAD_TIMEOUT_SEC,
    t.TASK_COMMENT,
    t.CLIENT_ACCOUNT,
    t.ENTRY_TIME        AS TASK_ENTRY_TIME,
    t.COMPLETED_TIME    AS TASK_COMPLETED_TIME,
    t.RUNTIME_ERROR
FROM
    {Schema}.UTIL_SYS_ETL_BATCH_STATUS_HIST   b
    JOIN
    {Schema}.UTIL_SYS_ETL_TASK_QUEUE_HIST     t
    ON t.BATCH_ID = b.BATCH_ID

WITH READ ONLY;
