CREATE OR REPLACE VIEW {Schema}.VIEW_UTIL_SYS_ETL_BATCH_STATUS AS
SELECT
    b.BATCH_ID,
    b.BATCH_STATUS,
    b.TASKS_COUNT,
    b.SCHEDULED_TIME,
    b.BATCH_COMMENT,
    b.ENTRY_TIME,
    b.TRIGGERED_TIME,
    NULL                AS COMPLETED_TIME,
    NULL                AS TIME_ELAPSED
FROM
    {Schema}.UTIL_SYS_ETL_BATCH_STATUS   b

UNION ALL

SELECT
    h.BATCH_ID,
    h.BATCH_STATUS,
    h.TASKS_COUNT,
    h.SCHEDULED_TIME,
    h.BATCH_COMMENT,
    h.ENTRY_TIME,
    h.TRIGGERED_TIME,
    h.COMPLETED_TIME,
    CAST(NUMTODSINTERVAL(h.COMPLETED_TIME - h.TRIGGERED_TIME, 'DAY') AS INTERVAL DAY(1) TO SECOND(0))   AS TIME_ELAPSED
FROM
    {Schema}.UTIL_SYS_ETL_BATCH_STATUS_HIST   h

WITH READ ONLY;
