CREATE OR REPLACE VIEW {Schema}.VIEW_UTIL_SYS_ETL_TASK_STATUS AS
SELECT
    t.BATCH_ID,
    t.STEP_PLAN,
    t.TASK_ID,
    t.EXTRACT_TYPE,
    t.EXTRACT_SOURCE,
    t.EXTRACT_COMMAND,
    t.EXTRACT_PARAMS,
    t.EXTRACT_TIMEOUT_SEC,
    t.RESULT_SET,
    t.NAMING_CONVENTION,
    t.LOAD_TYPE,
    t.FIELD_MAPPING,
    t.MERGE_PARAMS,
    t.LOAD_DESTINATION,
    t.LOAD_COMMAND,
    t.LOAD_TIMEOUT_SEC,
    t.TASK_COMMENT,
    t.CLIENT_ACCOUNT,
    t.ENTRY_TIME,
    t.COMPLETED_TIME,
    t.RUNTIME_ERROR
FROM
    {Schema}.UTIL_SYS_ETL_TASK_QUEUE     t

UNION ALL

SELECT
    h.BATCH_ID,
    h.STEP_PLAN,
    h.TASK_ID,
    h.EXTRACT_TYPE,
    h.EXTRACT_SOURCE,
    h.EXTRACT_COMMAND,
    h.EXTRACT_PARAMS,
    h.EXTRACT_TIMEOUT_SEC,
    h.RESULT_SET,
    h.NAMING_CONVENTION,
    h.LOAD_TYPE,
    h.FIELD_MAPPING,
    h.MERGE_PARAMS,
    h.LOAD_DESTINATION,
    h.LOAD_COMMAND,
    h.LOAD_TIMEOUT_SEC,
    h.TASK_COMMENT,
    h.CLIENT_ACCOUNT,
    h.ENTRY_TIME,
    h.COMPLETED_TIME,
    h.RUNTIME_ERROR
FROM
    {Schema}.UTIL_SYS_ETL_TASK_QUEUE_HIST     h

WITH READ ONLY;
